format = """
$time\
$username\
$hostname\
$shlvl\
$python\
$nodejs\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$memory_usage\
$jobs\
$battery\
$status\
$shell\
$character"""

add_newline = false

[time]
disabled = false
format = '[$time]($style) '
style = 'bold fg:red'

[git_branch]
format = "[$symbol$branch]($style) "

[status]
disabled = false

[python]
# customize the python promt so that it's compact (only shows the venv)
symbol = "🐍"
format = '[${symbol}($virtualenv) ]($style)'
# make it so that we only show the prompt if a virtualenv is active
detect_files = []
detect_extensions = []

[nodejs]
symbol = "🤖"
format = "[$symbol($version )]($style)"
