format = """
$time\
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$memory_usage\
$jobs\
$battery\
$status\
$shell\
$character"""

add_newline = false

[time]
disabled = false
format = '[$time]($style) '
style = 'bold fg:red'

[git_branch]
format = "[$symbol$branch]($style) "

[status]
disabled = false

